select
	day
    , COUNT(CASE WHEN HOUR=0 THEN 1 END) as '0'
    , COUNT(CASE WHEN HOUR=1 THEN 1 END) as '1'
    , COUNT(CASE WHEN HOUR=2 THEN 1 END) as '2'
    , COUNT(CASE WHEN HOUR=3 THEN 1 END) as '3'
    , COUNT(CASE WHEN HOUR=4 THEN 1 END) as '4'
    , COUNT(CASE WHEN HOUR=5 THEN 1 END) as '5'
	, COUNT(CASE WHEN HOUR=6 THEN 1 END) as '6'
    , COUNT(CASE WHEN HOUR=7 THEN 1 END) as '7'
    , COUNT(CASE WHEN HOUR=8 THEN 1 END) as '8'
    , COUNT(CASE WHEN HOUR=9 THEN 1 END) as '9'
    , COUNT(CASE WHEN HOUR=10 THEN 1 END) as '10'
    , COUNT(CASE WHEN HOUR=11 THEN 1 END) as '11'
    , COUNT(CASE WHEN HOUR=12 THEN 1 END) as '12'
    , COUNT(CASE WHEN HOUR=13 THEN 1 END) as '13'
    , COUNT(CASE WHEN HOUR=14 THEN 1 END) as '14'
    , COUNT(CASE WHEN HOUR=15 THEN 1 END) as '15'
    , COUNT(CASE WHEN HOUR=16 THEN 1 END) as '16'
    , COUNT(CASE WHEN HOUR=17 THEN 1 END) as '17'
    , COUNT(CASE WHEN HOUR=18 THEN 1 END) as '18'
    , COUNT(CASE WHEN HOUR=19 THEN 1 END) as '19'
    , COUNT(CASE WHEN HOUR=20 THEN 1 END) as '20'
    , COUNT(CASE WHEN HOUR=21 THEN 1 END) as '21'
    , COUNT(CASE WHEN HOUR=22 THEN 1 END) as '22'
    , COUNT(CASE WHEN HOUR=23 THEN 1 END) as '23'
from
	customerVisitData
group by
	WeatherDescription
    , CustomerDescription
    , HolidayDescription
	, day;